apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hook
  name: hook
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800"  
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.4"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always

      
