apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hook
  name: hook
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /rai
      name: primeiro-volume  
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-volume
    emptyDir:
      sizeLimit: 256Mi

      
