apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meu-nginx
  name: meu-nginx
spec: 
  replicas: 5
  selector: 
    matchLabels:
      app: meu-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: meu-nginx
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
              cpu: "0.25"
              memory: "128Mi"



