apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rai
  name: rai
spec:
  containers:
  - image: nginx
    name: rai
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
